# Generated by Django 6.0 on 2025-12-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nature_of_business', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('organisation_company', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('queries_partnership_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Business Enquiries',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('app', 'App / website'), ('profiles', 'Profiles & matching'), ('payments', 'Payment & plans'), ('safety', 'Safety / report user'), ('other', 'Other')], default='app', max_length=50)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('suggestions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Feedback & Suggestions',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(choices=[('bride', 'Bride'), ('groom', 'Groom'), ('lgbtq', 'LGBTQ+')], max_length=20)),
                ('derived_gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('transgender', 'Transgender'), ('gay', 'Gay'), ('lesbian', 'Lesbian'), ('bisexual', 'Bisexual'), ('queer', 'Queer')], max_length=20, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('height_cm', models.PositiveIntegerField()),
                ('weight_kg', models.PositiveIntegerField()),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('religion', models.CharField(max_length=100)),
                ('community', models.CharField(max_length=100)),
                ('sub_community', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('working_status', models.CharField(max_length=100)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('annual_income', models.CharField(blank=True, max_length=50, null=True)),
                ('diet', models.CharField(max_length=50)),
                ('drinking', models.CharField(max_length=50)),
                ('smoking', models.CharField(max_length=50)),
                ('hobbies', models.CharField(max_length=300)),
                ('about_me', models.TextField()),
                ('face_verified', models.BooleanField(default=False)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('id_type', models.CharField(max_length=50)),
                ('id_proof_front', models.FileField(upload_to='id_proofs/front/')),
                ('id_proof_back', models.FileField(blank=True, null=True, upload_to='id_proofs/back/')),
                ('selfie_image', models.FileField(blank=True, null=True, upload_to='photos/selfie/')),
                ('uploaded_photo', models.FileField(blank=True, null=True, upload_to='photos/uploaded/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
