# Generated by Django 6.0 on 2025-12-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
